In [3]:
# !pip install numpy
import numpy as np

In [7]:
l = [1,2,3,4,5,6]  # list
a = np.array(l)    # numpy array
print(a)
print(type(a))
print(a.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [8]:
# Operations

l = [1,2,3,4,5,6,7,8,9]
a = np.array(l)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [9]:
# shape : shows row and cloumn
a.shape

(9,)

In [11]:
# In numpy array rows and columns should be equal. Data should be structured.
# Two dimensional data

a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [12]:
# Three dimensional data

a = np.array([[[1],[2],[3]],
            [[4],[5],[6]],
            [[7],[8],[9]]])
print(a)
print(a.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [13]:
# In ouptut (3,3,1), the first 3 represent the data inside 1st big barcket, the second 3 represent the data inside 2nd big 
# bracket and the last 1 represent single value inside each bracket.

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.ones((6,6))+1

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [20]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
a = np.array([(1,2,3),
             (4,5,6)])
print(a)

# Using numpy we can also reshape the matrix

print(a.reshape(3,2))
print(a.reshape(2,3))
print(a.reshape(1,6))c
print(a.reshape(6,1))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [2]:
#flatten: converts multi-dimensioanl array into one dimensional

import numpy as np

a = np.array([(1,2,3),
             (4,5,6)])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [3]:
# Numpy array concatination

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a+b    # This adds up numbers instead of concatinating
print(c)

[ 7  9 11 13 15]


In [6]:
# Horizontal Stacking

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.hstack((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Vertical Stacking

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.vstack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
# Generating random number: generates values form 0 to 1 if choice is not specified

print(np.random.rand(2,2))
print(np.random.rand(5,5))

[[0.46823216 0.46890662]
 [0.50989808 0.84484125]]
[[0.15877276 0.07647637 0.73027716 0.04567508 0.37592542]
 [0.37222788 0.16506216 0.33069498 0.97625186 0.09346687]
 [0.52604738 0.77958849 0.29193097 0.65866585 0.30047041]
 [0.16242909 0.1292756  0.73565561 0.74568461 0.44251563]
 [0.49645239 0.54196526 0.90892824 0.40586229 0.0859986 ]]


In [9]:
print(np.random.randint(0,10, size=[2,2]))

[[7 5]
 [5 4]]


In [10]:
print(np.random.choice(['a','e','i','o','u'], size=10))

['u' 'o' 'u' 'i' 'u' 'o' 'u' 'a' 'i' 'a']


In [11]:
print(np.random.choice(['a','e','i','o','u'], size=(5,5)))

[['a' 'e' 'i' 'u' 'u']
 ['o' 'i' 'e' 'o' 'a']
 ['i' 'u' 'a' 'u' 'a']
 ['i' 'i' 'i' 'u' 'a']
 ['i' 'i' 'i' 'i' 'u']]


In [12]:
print(np.random.choice([0,1,2,3,4,5,6,7,8,9,'a','e','i','o','u'], size=16))

['i' '4' '8' '0' '8' '8' '1' '9' '0' 'a' 'i' 'a' '7' '3' '3' 'u']


In [13]:
"".join(np.random.choice([0,1,2,3,4,5,6,7,8,9,'a','e','i','o','u'], size=16))

'82a3u122ie76oo57'

In [15]:
b = np.random.randint(0,255, size=[10,10])
print(b)

[[185 225  13 242  47  17 108  79 108 119]
 [204 108 156 186 147  31 147 117 173 226]
 [220 200 242  18 193 177  63  72 125  64]
 [ 76 103 121 196  17 155 253 182  23 105]
 [ 33 135  74  24 146 154 243 175 138 156]
 [140 150 222 185 242  85 237 253 104 148]
 [ 15  33  50 129 110 111 117 102 242 206]
 [ 99  71  78  12 155  71  15 229  75  25]
 [221  10 175  52 183   0 188 253 107  76]
 [118 133 161 219  23  48 166  18  23  39]]


In [20]:
# Statistical Functions

a = np.array([123,456,789,655,456,345,67,89,654,234,33,45,65])
print("Minimum value = ",np.min(a))
print("Maximun value = ",np.max(a))
print("Mean value = ",np.mean(a))
print("Median value = ",np.median(a))
print("Standard Deviation value = ",np.std(a))

Minimum value =  33
Maximun value =  789
Mean value =  308.53846153846155
Median value =  234.0
Standard Deviation value =  258.1361046438682


In [21]:
# Matrix Operations

# To find determinant

import scipy.linalg as slin
import numpy as np

a = np.array([[3,-5,4],
            [8,4,2],
            [4,6,1]])
slin.det(a)

104.00000000000003

In [22]:
# Trace of matrix: adding diagonal of matrix (3+4+1)

a = np.array([[3,-5,4],
            [8,4,2],
            [4,6,1]])
np.trace(a)

8

In [24]:
# Inverse of Matrix

a = np.array([[3,-5,8],
            [-1,2,3],
            [-5,-6,2]])
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

In [27]:
# Transpose of Matrix

a = np.array([[3,-5,8],
            [-1,2,3],
            [-5,-6,2]])
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

In [28]:
# Matrix Multiplication

a=np.matrix([[ 3, -5, 8],
             [-1, 2, 3],
             [-5, -6, 2]])

b=np.matrix([[3],
             [4],
             [-1]])

a*b

matrix([[-19],
        [  2],
        [-41]])